In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV

In [ ]:
df=pd.read_csv(r"C:\Users\mnour\Desktop\amazon.csv")

In [4]:
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [5]:
df['num_reviews'] = df['review_id'].apply(lambda x: len(x.split(',')))
df[['main_cat','sub_cat','type']] = (
    df['category']
    .str.split('|', n=2, expand=True)
)
df['main_cat'] = df['main_cat'].str.strip()
df['sub_cat'] = df['sub_cat'].str.strip()
df['type'] = df['type'].str.strip()

In [6]:
df.shape

(1465, 20)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
 16  num_reviews          1465 non-null   int64
 17  main_cat             1465 non-null   object
 18  sub_cat              1465 non-null   object
 19  type                 1457 non-null   object
dtypes: int64(1), object(19)
memory usage: 229.0+ KB

In [8]:
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
num_reviews            0
main_cat               0
sub_cat                0
type                   8
dtype: int64

In [9]:
def clean_price(x):
    if pd.isna(x): return x
    return float(str(x).replace('₹', '').replace(',', ''))

df['discounted_price'] = df['discounted_price'].apply(clean_price)
df['actual_price'] = df['actual_price'].apply(clean_price)
df['discount_percentage'] = pd.to_numeric(df['discount_percentage'].str.replace('%', ''), errors='coerce')
df['rating_count'] = pd.to_numeric(df['rating_count'].str.replace(',', ''), errors='coerce')

df['rating'] = pd.to_numeric(df['rating'], errors='coerce')
df['rating'].fillna(df['rating'].mean(), inplace=True)

df['rating_count'].fillna(df['rating_count'].median(), inplace=True)


def cap_outliers(df, column, upper_percentile=0.95):
    upper_limit = df[column].quantile(upper_percentile)

    df[column] = np.where(df[column] > upper_limit, upper_limit, df[column])
    return df, upper_limit


df, price_limit = cap_outliers(df, 'actual_price')
df, count_limit = cap_outliers(df, 'rating_count')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   float64
 4   actual_price         1465 non-null   float64
 5   discount_percentage  1465 non-null   int64
 6   rating               1465 non-null   float64
 7   rating_count         1465 non-null   float64
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
 16  num_reviews          1465 non-null   int64
 17  main_cat             1465 non-null   object
 18  sub_cat              1465 non-null   object
 19  type                 1457 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 229.0+ KB

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.isna().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           0
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
num_reviews            0
main_cat               0
sub_cat                0
type                   8
dtype: int64

In [12]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
discounted_price,1465.0,3125.310874,6944.304394,39.0,325.0,799.0,1999.0,77990.0
actual_price,1465.0,4493.144901,6582.038272,39.0,800.0,1650.0,4295.0,24962.0
discount_percentage,1465.0,47.691468,21.635905,0.0,32.0,50.0,63.0,94.0
rating,1465.0,4.096585,0.291574,2.0,4.0,4.1,4.3,5.0
rating_count,1465.0,13664.133242,19546.729966,2.0,1191.0,5179.0,17325.0,74976.8
num_reviews,1465.0,7.851877,0.827654,1.0,8.0,8.0,8.0,8.0

In [13]:
df['price_diff'] = df['actual_price'] - df['discounted_price']


df['discount_ratio'] = df['discounted_price'] / df['actual_price']

df['rating_weighted'] = df['rating'] * df['rating_count']

df['discount_percentage'] = (
    df['actual_price'] - df['discounted_price']
) / df['actual_price']

In [14]:
df.to_csv('amazon_ready_for_analysis.csv', index=False)

In [15]:
y = df['rating']
X = df[
    [
        'actual_price',
        'discounted_price',
        'price_diff',
        'discount_ratio',
        'rating_count',
        'main_cat'
    ]
]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
num_features = [
    'actual_price',
    'discounted_price',
    'price_diff',
    'discount_ratio',
    'rating_count'
]

cat_features = ['main_cat']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', num_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_features)
    ]
)

In [18]:
lr_model = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', LinearRegression())
    ]
)

lr_model.fit(X_train, y_train)

y_pred_lr = lr_model.predict(X_test)

print("Linear Regression")
print("MAE:", mean_absolute_error(y_test, y_pred_lr))
print("R2 :", r2_score(y_test, y_pred_lr))

Linear Regression
MAE: 0.19626211881056194
R2 : 0.12930427214395257

In [19]:
from sklearn.ensemble import RandomForestRegressor

rf_model = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', RandomForestRegressor(
            n_estimators=200,
            max_depth=10,
            random_state=42
        ))
    ]
)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

print("Random Forest Regressor")
print("MAE:", mean_absolute_error(y_test, y_pred_rf))
print("R2 Score:", r2_score(y_test, y_pred_rf))

Random Forest Regressor
MAE: 0.17643222098166467
R2 Score: 0.1631196748553928

In [20]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf_clf = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', RandomForestClassifier(
            n_estimators=200,
            max_depth=10,
            random_state=42
        ))
    ]
)
rf_clf.fit(X_train, y_train.astype(int))
y_pred_clf = rf_clf.predict(X_test)
print("Random Forest Classifier")
print("Accuracy:", accuracy_score(y_test.astype(int), y_pred_clf))

Random Forest Classifier
Accuracy: 0.7610921501706485

In [21]:
from sklearn.preprocessing import LabelEncoder

label=LabelEncoder()
cat=df.select_dtypes(include='object').columns
for i in cat:
  df[i]=label.fit_transform(df[i])

In [22]:
x=df.drop("rating",axis=1)
y=df["rating"]

In [23]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [24]:
from sklearn.preprocessing import RobustScaler
print("\n--- Feature Scaling with RobustScaler ---")
scaler = RobustScaler()

--- Feature Scaling with RobustScaler ---

In [25]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [26]:
model=LinearRegression()
model.fit(X_train,y_train)
y_pred_linear=model.predict(X_test)
r2 = r2_score(y_test, y_pred_linear)
print(f"R² Score: {r2:.4f}")

R² Score: 0.2813

In [27]:

from sklearn.linear_model import Lasso


lasso = Lasso(alpha=0.1, random_state=42)
lasso.fit(X_train, y_train)
y_pred_lasso = lasso.predict(X_test)
r2_lasso = r2_score(y_test, y_pred_lasso)

print(f"Lasso R² Score: {r2_lasso:.4f}")

Lasso R² Score: 0.0025

In [28]:

from sklearn.ensemble import GradientBoostingRegressor


model = GradientBoostingRegressor(
    n_estimators=100,   
    learning_rate=0.1,  
    max_depth=3,        
    random_state=42
)

model.fit(X_train, y_train)
y_pred_gradient = model.predict(X_test)

In [29]:
r2 = r2_score(y_test, y_pred_gradient)
print(f"R-squared: {r2:.4f}")
score = model.score(X_test, y_test)
print("Accuracy:", score)

R-squared: 0.1786
Accuracy: 0.17855917550538136

In [30]:
le = LabelEncoder()
for col in ['main_cat', 'sub_cat', 'type']:
    df[col] = le.fit_transform(df[col])


features=['actual_price', 'discounted_price', 'price_diff', 'discount_ratio', 'rating_count', 'main_cat', 'sub_cat', 'type']
X = df[features]
y = df["rating"].astype(int)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, stratify=y, random_state=3)

param_grid = {
    'n_estimators': [200, 500], 
    'max_depth': [10, 20, 30, None], 
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False]
}
grid_search = GridSearchCV(RandomForestClassifier(random_state=42), param_grid, cv=5)
grid_search.fit(X_train, y_train)


best_model = grid_search.best_estimator_
predictions = best_model.predict(X_test)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           2       0.00      0.00      0.00         1
           3       0.70      0.32      0.44        87
           4       0.82      0.96      0.88       278
           5       0.00      0.00      0.00         1

    accuracy                           0.80       367
   macro avg       0.38      0.32      0.33       367
weighted avg       0.78      0.80      0.77       367

In [36]:
sample = pd.DataFrame({
    'actual_price': [5000],
    'discounted_price': [4000],
    'price_diff': [1000],
    'discount_ratio': [0.8],
    'rating_count': [300],
    'main_cat': ['Electronics'],
    'sub_cat': ['Laptops'], 
    'type': ['High-End']
})


features = ['actual_price', 'discounted_price', 'price_diff', 'discount_ratio', 'rating_count', 'main_cat', 'sub_cat', 'type']

sample['main_cat'] = 0  
sample['sub_cat'] = 0
sample['type'] = 0

sample = sample[features]


prediction = best_model.predict(sample)
print(f"The predicted rating is: {prediction[0]}")

The predicted rating is: 4